#!/bin/bash
sudo yum update -y
sudo yum install httpd mariadb105.x86_64 php8.1.x86_64 -y
sudo su 
rm -f /var/www/html/*
touch /var/www/html/phpinfo.php
echo "<?php phpinfo(); ?>" > /var/www/html/info.php 
systemctl start httpd
systemctl enable httpd
