#!/bin/bash
sudo yum update -y
sudo yum install httpd mariadb105.x86_64 php8.1.x86_64 -y
sudo su 
cd /var/www/html/
touch info.php
echo "<?php phpinfo(); ?>" > info.php 
systemctl start httpd
systemctl enable httpd
